"""empty message

Revision ID: 0d07d25b06f0
Revises: df8102ba7871
Create Date: 2020-08-05 15:53:25.416856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d07d25b06f0'
down_revision = 'df8102ba7871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('restaurants_nom_key', 'restaurants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('restaurants_nom_key', 'restaurants', ['nom'])
    op.drop_column('restaurants', 'id')
    # ### end Alembic commands ###
