"""empty message

Revision ID: 9c5fda49bf24
Revises: a31ccde2a465
Create Date: 2020-07-24 16:29:01.499492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c5fda49bf24'
down_revision = 'a31ccde2a465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('name', table_name='departments')
    op.drop_table('departments')
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    op.drop_constraint('employees_ibfk_2', 'employees', type_='foreignkey')
    op.drop_column('employees', 'role_id')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_ibfk_2', 'employees', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('employees_ibfk_1', 'employees', 'departments', ['department_id'], ['id'])
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'departments', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
