"""empty message

Revision ID: df8102ba7871
Revises: 
Create Date: 2020-08-05 13:51:57.795103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8102ba7871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constructeur', sa.String(length=60), nullable=True),
    sa.Column('modele', sa.String(length=60), nullable=True),
    sa.Column('kilometrage', sa.String(length=60), nullable=True),
    sa.Column('carburant', sa.String(length=60), nullable=True),
    sa.Column('annee', sa.String(length=60), nullable=True),
    sa.Column('localisation', sa.String(length=60), nullable=True),
    sa.Column('contact', sa.String(length=60), nullable=True),
    sa.Column('transmission', sa.String(length=60), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('vendeur', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=228), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_first_name'), 'employee', ['first_name'], unique=False)
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    op.create_table('immobilier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('intitule', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('monnaie', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('surface', sa.Integer(), nullable=True),
    sa.Column('chambre', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offres',
    sa.Column('intitule', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('secteur', sa.Text(), nullable=True),
    sa.Column('salaire', sa.Text(), nullable=True),
    sa.Column('typeContrat', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('niveau', sa.Text(), nullable=True),
    sa.Column('entreprise', sa.Text(), nullable=True),
    sa.Column('lieu', sa.Text(), nullable=True),
    sa.Column('pays', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('lien', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('lien')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('pays', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants')
    op.drop_table('offres')
    op.drop_table('immobilier')
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_first_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('car')
    # ### end Alembic commands ###
